"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Action={id:string;text:string;estimated_minutes:number}; type Execution={session_id:string;action:Action}; type Accountability={id:string;participant_label:string;status:string};
export default function Accountability(){const[action,setAction]=useState<Action|null>(null),[session,setSession]=useState<Execution|null>(null),[accountability,setAccountability]=useState<Accountability|null>(null),[label,setLabel]=useState("lokale buddy"),[message,setMessage]=useState("Kies een actie om samen gefocust te werken.");
 useEffect(()=>{fetch(`${API}/api/sessions/active`).then(r=>r.ok?r.json():null).then(data=>{if(data){setSession(data);setMessage("Actieve focus-sessie hersteld. Je kunt een lokale buddy toevoegen.")}})},[]);
 async function pick(){const r=await fetch(`${API}/api/mcp/current-action`);if(!r.ok){setMessage("Geen actie beschikbaar.");return}setAction(await r.json());setMessage("Actie gevonden. Start de actie en voeg daarna een accountability buddy toe.")}
 async function start(){if(!action)return;const r=await fetch(`${API}/api/actions/${action.id}/start`,{method:"POST"});if(!r.ok){setMessage("Actie kon niet starten.");return}const data=await r.json();setSession(data);setMessage("Actie gestart. Je kunt nu een lokale buddy-sessie openen.")}
 async function join(){if(!session)return;const r=await fetch(`${API}/api/accountability/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({execution_session_id:session.session_id,participant_label:label})});if(!r.ok){setMessage("Buddy-sessie kon niet starten.");return}setAccountability(await r.json());setMessage("Accountability actief. Werk samen tot je klaar bent.")}
 async function leave(status:"completed"|"stopped"){if(!accountability)return;const r=await fetch(`${API}/api/accountability/${accountability.id}/finish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(r.ok){setAccountability(await r.json());setMessage(status==="completed"?"Accountability afgerond.":"Accountability gestopt.")}}
 return <main><header><span className="logo">ADD</span><span>Accountability</span><a className="lab-link" href="/focus">Focus</a></header><section className="lab-hero"><p className="eyebrow">BODY DOUBLING</p><h1>Werk samen aan één actie.</h1><p className="meta">Een lokale buddy-sessie houdt je bij de uitvoering. Er worden geen externe accounts of berichten gebruikt.</p>{!action&&!session&&<button onClick={pick}>Kies een actie</button>}{action&&!session&&<section className="suggestion"><h2>{action.text}</h2><p className="meta">ongeveer {action.estimated_minutes} minuten</p><button onClick={start}>Start actie</button></section>}{session&&!accountability&&<section className="suggestion"><h2>Actie loopt</h2><p>{session.action.text}</p><label className="lab-fields">Buddy-label<input value={label} onChange={e=>setLabel(e.target.value)}/></label><button onClick={join}>Start accountability</button></section>}{accountability&&<section className="suggestion"><h2>Accountability actief</h2><p>Buddy: {accountability.participant_label}</p><div className="actions"><button onClick={()=>leave("completed")}>Sessie afgerond</button><button className="quiet" onClick={()=>leave("stopped")}>Stop accountability</button></div></section>}<p className="message">{message}</p></section></main>}
