"use client";

import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type BadgeMode = "hidden" | "dot" | "count";
type LLMProvider = "openrouter";
type FreeModel = { id: string; name: string; context_length?: number | null };
type SettingLink = { href: string; title: string; detail: string };
type SettingGroup = { eyebrow: string; title: string; description: string; items: SettingLink[] };
type Category = { id: string; eyebrow: string; title: string; description: string; count: number };

const groups: SettingGroup[] = [
  { eyebrow: "WERKSTROOM", title: "Werkstroom", description: "Verwerk, plan en evalueer je werk.", items: [
    { href: "/review", title: "Inbox review", detail: "Inkomende taken één voor één beslissen." }, { href: "/intake", title: "Vastleggen", detail: "Een nieuwe taak snel opslaan." }, { href: "/views", title: "Later en views", detail: "Open werk en opgeslagen lenzen." }, { href: "/today", title: "Vandaag", detail: "Tijd blokkeren en herplannen." }, { href: "/daily-review", title: "Dagreview", detail: "De planning afronden." }, { href: "/history", title: "Geschiedenis", detail: "Eerdere pogingen terugzien." },
  ] },
  { eyebrow: "UITVOERING", title: "Focus en ondersteuning", description: "Optionele hulpmiddelen rond één volgende actie.", items: [
    { href: "/execute", title: "Uitvoeren", detail: "Een actie starten en afronden." }, { href: "/focus", title: "Focus", detail: "Een begrensde focussessie." }, { href: "/accountability", title: "Accountability", detail: "Samen gefocust werken." }, { href: "/unstuck", title: "Vastgelopen", detail: "Een actie kleiner maken." },
  ] },
  { eyebrow: "VERBINDINGEN", title: "Integraties", description: "Externe bronnen en veilige verbindingen.", items: [
    { href: "/integrations", title: "Integratiehub", detail: "Alle verbindingen vanaf één plek." }, { href: "/ha", title: "Home Assistant", detail: "Context en mirror." }, { href: "/mcp", title: "MCP / Hermes", detail: "Protocol en tools testen." }, { href: "/outbox", title: "Outbox", detail: "Uitgaande events controleren." }, { href: "/connectors/gmail", title: "Gmail", detail: "Email als voorstel ontvangen." }, { href: "/connectors/calendar", title: "Calendar", detail: "Afspraken als voorstel ontvangen." }, { href: "/connectors/whatsapp", title: "WhatsApp", detail: "Berichten als voorstel ontvangen." },
  ] },
  { eyebrow: "AUTOMATISERING", title: "Routines en reminders", description: "Rustige herhaling zonder automatische uitvoering.", items: [{ href: "/routines", title: "Routines", detail: "Terugkerende patronen beheren." }, { href: "/reminders", title: "Reminders", detail: "Contextuele reminders previewen." }] },
  { eyebrow: "TAAL", title: "Communicatie", description: "Tekst voorbereiden en verbeteren.", items: [{ href: "/communications", title: "Communicatiehulp", detail: "Concepten en tekstassistentie." }] },
  { eyebrow: "SYSTEEM", title: "Gegevens en veiligheid", description: "Beheer de lokale installatie.", items: [{ href: "/backup", title: "Backup", detail: "Data downloaden en herstellen." }, { href: "/security", title: "Beveiliging", detail: "Login en credentials." }, { href: "/status", title: "Systeemstatus", detail: "API, database en integraties." }, { href: "/setup", title: "Eerste setup", detail: "Installatie opnieuw controleren." }] },
];

const linkedGroups: Record<string, SettingGroup> = { workflow: groups[0], focus: groups[1], connections: groups[2], automation: groups[3], language: groups[4], system: groups[5] };
const categories: Category[] = [
  { id: "display", eyebrow: "WEERGAVE", title: "Workflow-badges", description: "Rust en visuele signalen", count: 1 }, { id: "assistant", eyebrow: "TAAKHULP", title: "Taakassistent", description: "Taken kleiner en duidelijker maken", count: 2 }, { id: "workflow", eyebrow: "WERKSTROOM", title: "Werkstroom", description: "Inbox, planning en review", count: groups[0].items.length }, { id: "focus", eyebrow: "UITVOERING", title: "Focus en ondersteuning", description: "Eén volgende actie uitvoeren", count: groups[1].items.length }, { id: "connections", eyebrow: "VERBINDINGEN", title: "Integraties", description: "Externe bronnen en koppelingen", count: groups[2].items.length }, { id: "automation", eyebrow: "AUTOMATISERING", title: "Routines en reminders", description: "Rustige herhaling", count: groups[3].items.length }, { id: "language", eyebrow: "TAAL", title: "Communicatie", description: "Tekst voorbereiden", count: groups[4].items.length }, { id: "system", eyebrow: "SYSTEEM", title: "Gegevens en veiligheid", description: "Lokale installatie beheren", count: groups[5].items.length },
];

export default function Settings() {
  const [badgeMode, setBadgeMode] = useState<BadgeMode>("dot"); const [mailPollEnabled, setMailPollEnabled] = useState(false); const [secureCookies, setSecureCookies] = useState(false); const [corsOrigins, setCorsOrigins] = useState("http://localhost:3000"); const [pollInterval, setPollInterval] = useState(900); const [syncBatch, setSyncBatch] = useState(25); const [cleanupConfidence, setCleanupConfidence] = useState(0.99); const [githubRepo, setGithubRepo] = useState("rbnbrls/add"); const [apiToken, setApiToken] = useState(""); const [githubToken, setGithubToken] = useState(""); const [assistantPrompt, setAssistantPrompt] = useState(""); const [llmProvider, setLlmProvider] = useState<LLMProvider>("openrouter"); const [llmModel, setLlmModel] = useState("openrouter/free"); const [freeModels, setFreeModels] = useState<FreeModel[]>([{ id: "openrouter/free", name: "OpenRouter Free Router" }]); const [llmApiKey, setLlmApiKey] = useState(""); const [llmConfigured, setLlmConfigured] = useState(false); const [message, setMessage] = useState("");
  async function loadFreeModels() { const response = await fetch(`${API}/api/llm/models`); if (!response.ok) return; const data = await response.json(); if (data.models?.length) setFreeModels(data.models); }
  useEffect(() => { Promise.all([fetch(`${API}/api/preferences`), fetch(`${API}/api/llm-settings`)]).then(async ([preferences, llm]) => { const data = preferences.ok ? await preferences.json() : null; const config = llm.ok ? await llm.json() : null; if (data?.workflow_badge_mode) setBadgeMode(data.workflow_badge_mode); setMailPollEnabled(Boolean(data?.mail_poll_enabled)); setSecureCookies(Boolean(data?.secure_cookies)); if (data?.api_cors_origins) setCorsOrigins(data.api_cors_origins); if (data?.mail_poll_interval_seconds) setPollInterval(data.mail_poll_interval_seconds); if (data?.mail_sync_batch_size) setSyncBatch(data.mail_sync_batch_size); if (data?.mail_auto_cleanup_confidence) setCleanupConfidence(data.mail_auto_cleanup_confidence); if (data?.github_repo) setGithubRepo(data.github_repo); if (data?.task_assistant_prompt) setAssistantPrompt(data.task_assistant_prompt); if (config?.provider) setLlmProvider(config.provider); if (config?.model) setLlmModel(config.model); setLlmConfigured(Boolean(config?.configured)); await loadFreeModels(); }).catch(() => setMessage("Instellingen konden niet worden geladen.")); }, []);
  async function savePreference(patch: Record<string, unknown>, success = "Voorkeur opgeslagen.") { const response = await fetch(`${API}/api/preferences`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workflow_badge_mode: badgeMode, mail_poll_enabled: mailPollEnabled, secure_cookies: secureCookies, api_cors_origins: corsOrigins, mail_poll_interval_seconds: pollInterval, mail_sync_batch_size: syncBatch, mail_auto_cleanup_confidence: cleanupConfidence, github_repo: githubRepo, ...patch }) }); setMessage(response.ok ? success : "Voorkeur kon niet worden opgeslagen."); return response.ok; }
  async function changeBadgeMode(value: BadgeMode) { setBadgeMode(value); await savePreference({ workflow_badge_mode: value }); }
  async function changeMailPoll(value: boolean) { setMailPollEnabled(value); const ok = await savePreference({ mail_poll_enabled: value }, value ? "Mail polling aangezet." : "Mail polling uitgezet."); if (!ok) setMailPollEnabled(!value); }
  async function saveAssistantPrompt() { await savePreference({ task_assistant_prompt: assistantPrompt }, "LLM-prompt opgeslagen."); }
  async function saveLlmSettings() { const response = await fetch(`${API}/api/preferences`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workflow_badge_mode: badgeMode, mail_poll_enabled: mailPollEnabled, secure_cookies: secureCookies, api_cors_origins: corsOrigins, mail_poll_interval_seconds: pollInterval, mail_sync_batch_size: syncBatch, mail_auto_cleanup_confidence: cleanupConfidence, github_repo: githubRepo, llm_provider: llmProvider, llm_base_url: "https://openrouter.ai/api/v1", llm_model: llmModel, llm_api_key: llmApiKey || undefined }) }); const data = await response.json().catch(() => null); setMessage(response.ok ? "Gratis LLM-provider opgeslagen." : data?.detail || "LLM-provider kon niet worden opgeslagen."); if (response.ok) { setLlmApiKey(""); setLlmConfigured(true); await loadFreeModels(); } }
  async function saveRuntimeSettings() { const ok = await savePreference({ api_token: apiToken || undefined, github_token: githubToken || undefined }, "Systeeminstellingen opgeslagen."); if (ok) { setApiToken(""); setGithubToken(""); } }
  function renderLinks(group: SettingGroup) { return <div className="settings-links">{group.items.map(item => <a className="settings-link" href={item.href} key={item.href}><span><strong>{item.title}</strong><small>{item.detail}</small></span><span className="settings-arrow" aria-hidden="true">→</span></a>)}</div>; }
  function renderCategory(category: Category) {
    const summary = <summary><span><b className="eyebrow">{category.eyebrow}</b><strong>{category.title}</strong><small>{category.description}</small></span><em>{category.count} {category.count === 1 ? "functie" : "functies"}</em></summary>;
    if (category.id === "display") return <details className="settings-accordion" id={category.id} key={category.id}>{summary}<div className="settings-accordion-body"><div className="settings-group-heading"><div><h2>Workflow-badges</h2></div><p className="meta">Bepaal hoeveel visuele signalen je op de landkaart wilt zien.</p></div><div className="badge-options" role="radiogroup" aria-label="Toon workflow-badges">{([["hidden", "Verborgen"], ["dot", "Alleen stip"], ["count", "Aantallen"]] as [BadgeMode, string][]).map(([value, label]) => <label key={value}><input type="radio" name="badge-mode" checked={badgeMode === value} onChange={() => void changeBadgeMode(value)} />{label}</label>)}</div></div></details>;
    if (category.id === "assistant") return <details className="settings-accordion" id={category.id} key={category.id}>{summary}<div className="settings-accordion-body"><div className="settings-group-heading"><div><h2>Prompt voor taakassistent</h2></div><p className="meta">Deze prompt wordt gebruikt wanneer je een taak laat opsplitsen in kleinere subtaken.</p></div><label className="settings-prompt-label">Prompt voor taakassistent<textarea value={assistantPrompt} onChange={event => setAssistantPrompt(event.target.value)} rows={4} placeholder="Help me deze taak concreet en klein te maken…" /></label><button type="button" className="secondary" onClick={() => void saveAssistantPrompt()}>Prompt opslaan</button><div className="settings-subsection"><div className="settings-group-heading"><div><p className="eyebrow">LLM-PROVIDER</p><h2>Gratis OpenRouter-modellen</h2></div><p className="meta">{llmConfigured ? "Er staat al een sleutel klaar." : "Nog geen sleutel ingesteld."}</p></div><div className="settings-llm-grid"><label>Provider<select value={llmProvider} disabled><option value="openrouter">OpenRouter</option></select></label><label>Gratis model<select value={llmModel} onChange={event => setLlmModel(event.target.value)}>{freeModels.map(model => <option value={model.id} key={model.id}>{model.name}</option>)}</select></label><label className="settings-llm-url">API endpoint<input value="https://openrouter.ai/api/v1" readOnly /></label><label className="settings-llm-key">API-key<input type="password" value={llmApiKey} onChange={event => setLlmApiKey(event.target.value)} placeholder={llmConfigured ? "Laat leeg om de huidige sleutel te behouden" : "Plak je OpenRouter API-key"} autoComplete="new-password" /></label></div><p className="meta">De Free Router kiest automatisch een beschikbaar gratis model.</p><button type="button" className="secondary" onClick={() => void saveLlmSettings()}>Gratis provider opslaan</button></div></div></details>;
    if (category.id === "automation") return <details className="settings-accordion" id={category.id} key={category.id}>{summary}<div className="settings-accordion-body"><div className="settings-group-heading"><div><h2>Mail polling</h2></div><p className="meta">Laat ADD periodiek nieuwe mail ophalen. De server verwerkt actieve mailboxen iedere 15 minuten; je hoeft geen environment variables aan te passen.</p></div><label className="check"><input type="checkbox" checked={mailPollEnabled} onChange={event => void changeMailPoll(event.target.checked)} /> Mail polling aanzetten</label><p className="meta">Zet eerst minstens één mailbox aan via <a href="/mail">Mail intake</a>. Uitschrijven en opruimen blijft beperkt tot de ingestelde veilige acties.</p><div className="settings-subsection">{renderLinks(linkedGroups[category.id])}</div></div></details>;
    if (category.id === "system") return <details className="settings-accordion" id={category.id} key={category.id}>{summary}<div className="settings-accordion-body"><div className="settings-group-heading"><div><h2>Applicatie-instellingen</h2></div><p className="meta">Deze waarden worden door ADD opgeslagen. Docker-, database- en poortinstellingen blijven deploymentconfiguratie.</p></div><div className="settings-llm-grid"><label>API CORS origins<input value={corsOrigins} onChange={e=>setCorsOrigins(e.target.value)} placeholder="http://localhost:3000" /></label><label>Mail sync interval (seconden)<input type="number" min={60} max={86400} value={pollInterval} onChange={e=>setPollInterval(Number(e.target.value))} /></label><label>Mail batchgrootte<input type="number" min={1} max={100} value={syncBatch} onChange={e=>setSyncBatch(Number(e.target.value))} /></label><label>Cleanup confidence<input type="number" min={0.5} max={1} step={0.01} value={cleanupConfidence} onChange={e=>setCleanupConfidence(Number(e.target.value))} /></label><label>GitHub repository<input value={githubRepo} onChange={e=>setGithubRepo(e.target.value)} placeholder="owner/repository" /></label><label>Nieuwe API-token<input type="password" value={apiToken} onChange={e=>setApiToken(e.target.value)} placeholder="leeg laten = behouden" autoComplete="new-password" /></label><label>GitHub token<input type="password" value={githubToken} onChange={e=>setGithubToken(e.target.value)} placeholder="leeg laten = behouden" autoComplete="new-password" /></label></div><label className="check"><input type="checkbox" checked={secureCookies} onChange={e=>setSecureCookies(e.target.checked)} /> Secure cookies gebruiken (HTTPS)</label><button type="button" className="secondary" onClick={()=>void saveRuntimeSettings()}>Systeeminstellingen opslaan</button><div className="settings-subsection">{renderLinks(linkedGroups[category.id])}</div></div></details>;
    return <details className="settings-accordion" id={category.id} key={category.id}>{summary}<div className="settings-accordion-body">{renderLinks(linkedGroups[category.id])}</div></details>;
  }
  return <main className="settings-shell"><header><span className="logo">ADD</span><span>Instellingen</span><a className="lab-link" href="/overview">Overzicht</a></header><section className="hero settings-hero"><p className="eyebrow">INSTELLINGEN</p><h1>Rustig overzicht.</h1><p className="meta">Alle functies staan hieronder. Open alleen de categorie die je nodig hebt.</p></section><nav className="settings-overview" aria-label="Instellingencategorieën"><p className="eyebrow">SNEL KIEZEN</p><div className="settings-overview-grid">{categories.map(category => <a href={`#${category.id}`} key={category.id}><span><strong>{category.title}</strong><small>{category.description}</small></span><em>{category.count}</em></a>)}</div></nav>{message && <p className="message settings-feedback" role="status">{message}</p>}<div className="settings-groups">{categories.map(renderCategory)}</div></main>;
}
