"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Credential={provider:string;updated_at:string};
const providers={"home-assistant":"Home Assistant",gmail:"Gmail",calendar:"Calendar",whatsapp:"WhatsApp"};

export default function Security(){
 const[step,setStep]=useState(1),[provider,setProvider]=useState("home-assistant"),[value,setValue]=useState(""),[items,setItems]=useState<Credential[]>([]),[message,setMessage]=useState(""),[login,setLogin]=useState(false),[key,setKey]=useState(false),[vault,setVault]=useState<boolean|null>(null);
 async function load(){const r=await fetch(`${API}/api/security/credentials`,{credentials:"include"});if(r.ok)setItems(await r.json())}
 async function status(){const r=await fetch(`${API}/api/auth/status`,{credentials:"include"});if(r.ok){const d=await r.json();setLogin(d.login_configured);setKey(d.encryption_configured)}}
 async function checkVault(){const r=await fetch(`${API}/api/security/credentials/check`,{credentials:"include"});if(r.ok){const d=await r.json();setVault(d.ok);setMessage(d.ok?"Kluis gecontroleerd.":"Controle van kluis nodig.")}}
 async function save(){const r=await fetch(`${API}/api/security/credentials/${provider}`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({value})});if(r.ok){setValue("");setStep(1);setMessage(`${providers[provider as keyof typeof providers]} is veilig opgeslagen.`);load();checkVault()}else setMessage("Opslaan is niet gelukt.")}
 async function remove(name:string){const r=await fetch(`${API}/api/security/credentials/${name}`,{method:"DELETE",credentials:"include"});if(r.ok){setMessage(`${providers[name as keyof typeof providers]||name} verwijderd.`);load();checkVault()}}
 useEffect(()=>{status();load();checkVault()},[]);
 return <main className="security-shell"><header><span className="logo">ADD</span><span>Beveiliging</span><a className="lab-link" href="/">NU</a></header><section className="hero"><p className="eyebrow">CONFIGURATIEWIZARD · STAP {step} VAN 4</p>{step===1&&<><h1>Controleer je kluis.</h1><p className="meta">Deze lokale installatie is {login?"afgeschermd met login":"nog niet afgeschermd met login"} en gebruikt {key?"een ingestelde":"een lokale fallback-"} encryptiesleutel.</p>{vault!==null&&<p className="message">Kluis: {vault?"gecontroleerd":"controle nodig"}.</p>}<div className="intake-form">{login?<button onClick={()=>setStep(2)}>Naar integraties</button>:<a className="primary-link" href="/security/setup">Lokale login instellen</a>}</div></>}{step===2&&<><h1>Kies een verbinding.</h1><p className="meta">Welke integratie wil je veilig toevoegen?</p><div className="intake-form"><label>Provider<select autoFocus value={provider} onChange={e=>setProvider(e.target.value)}>{Object.entries(providers).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button onClick={()=>setStep(3)}>Verder</button></div></>}{step===3&&<><h1>Voer het geheim in.</h1><p className="meta">Alleen opslaan; ADD toont deze waarde nooit terug.</p><div className="intake-form"><label>{providers[provider as keyof typeof providers]} credential<input autoFocus type="password" value={value} onChange={e=>setValue(e.target.value)} placeholder="Plak hier de geheime waarde" autoComplete="new-password"/></label><button disabled={!value.trim()} onClick={()=>setStep(4)}>Controleer</button></div></>}{step===4&&<><h1>Klaar om op te slaan?</h1><p className="meta">{providers[provider as keyof typeof providers]} · waarde verborgen</p><div className="actions"><button onClick={save}>Versleuteld opslaan</button><button className="quiet" onClick={()=>setStep(3)}>Terug</button></div></>}<p className="message">{message}</p></section>{items.length>0&&<section className="context"><h2>Opgeslagen providers</h2>{items.map(item=><div className="pending-item" key={item.provider}><div><strong>{providers[item.provider as keyof typeof providers]||item.provider}</strong><span className="meta">versleuteld · {new Date(item.updated_at).toLocaleString("nl-NL")}</span></div><button className="quiet" onClick={()=>remove(item.provider)}>Verwijder</button></div>)}</section>}</main>
}
