"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";const KEY="add-ha-context";
type Action={text:string;estimated_minutes:number;energy:string}|null;type Config={delivery_mode:string;poll_mode:string};
export default function HomeAssistant(){const[energy,setEnergy]=useState("medium"),[isHome,setIsHome]=useState(true),[computer,setComputer]=useState(true),[action,setAction]=useState<Action>(null),[config,setConfig]=useState<Config|null>(null),[message,setMessage]=useState(""),[ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||"null");if(saved){setEnergy(saved.energy||"medium");setIsHome(saved.isHome!==false);setComputer(saved.computer!==false)}}catch{}setReady(true);fetch(`${API}/api/ha/config`).then(r=>r.ok?r.json():null).then(setConfig)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify({energy,isHome,computer}))},[ready,energy,isHome,computer]);
 async function choose(){const p=new URLSearchParams({is_home:String(isHome),energy,computer_available:String(computer)});const r=await fetch(`${API}/api/ha/now?${p}`);if(r.ok){setAction(await r.json());setMessage("")}else{setAction(null);setMessage("Geen passende actie in deze context.")}}
 return <main className="ha-shell"><header><span className="logo">ADD</span><span>Home Assistant</span><a className="lab-link" href="/">NU</a></header><section className="hero"><p className="eyebrow">CONTEXT → ACTIE</p><h1>Wat past er nu?</h1><p className="meta">Je context wordt onthouden op dit apparaat.</p><div className="ha-context"><label>Energie<select value={energy} onChange={e=>setEnergy(e.target.value)}><option value="low">laag</option><option value="medium">medium</option><option value="high">hoog</option></select></label><label className="check"><input type="checkbox" checked={isHome} onChange={e=>setIsHome(e.target.checked)}/> Thuis</label><label className="check"><input type="checkbox" checked={computer} onChange={e=>setComputer(e.target.checked)}/> Computer</label></div><button onClick={choose}>Toon mijn actie</button><p className="message">{message}</p></section>{action&&<section className="suggestion"><p className="eyebrow">NU UITVOERBAAR</p><h2>{action.text}</h2><p className="meta">{action.estimated_minutes} minuten · {action.energy} energie</p><a className="primary-link" href="/execute">Open in ADD</a></section>}{config&&<p className="ha-status">HA: {config.poll_mode} context · {config.delivery_mode} mirror</p>}<details className="ha-advanced"><summary>Technische testopties</summary><p className="meta">Voor events, loop-preventie, outbox en live polling.</p><a href="/integrations">Open Integration Lab</a></details></main>}
