export type OfflineAction={id:string;text:string;estimated_minutes:number;energy:string};
export type OfflineMutation={id:string;action_id:string;outcome:string;started_at:string;stuck_reason?:string};
export type OfflineConflict={id:string;action_id:string;outcome:string;detail:string;created_at:string};
const DB_NAME="add-offline", VERSION=2;
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("state"))db.createObjectStore("state");if(!db.objectStoreNames.contains("mutations"))db.createObjectStore("mutations",{keyPath:"id"});if(!db.objectStoreNames.contains("conflicts"))db.createObjectStore("conflicts",{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function saveAction(action:OfflineAction){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("state","readwrite");tx.objectStore("state").put(action,"next");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function getAction(){const db=await open();return new Promise<OfflineAction|null>((resolve,reject)=>{const tx=db.transaction("state");const request=tx.objectStore("state").get("next");request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}
export async function saveMutation(mutation:OfflineMutation){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("mutations","readwrite");tx.objectStore("mutations").put(mutation);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function getMutations(){const db=await open();return new Promise<OfflineMutation[]>((resolve,reject)=>{const tx=db.transaction("mutations");const request=tx.objectStore("mutations").getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error)})}
export async function deleteMutation(id:string){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("mutations","readwrite");tx.objectStore("mutations").delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function saveConflict(conflict:OfflineConflict){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("conflicts","readwrite");tx.objectStore("conflicts").put(conflict);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function getConflicts(){const db=await open();return new Promise<OfflineConflict[]>((resolve,reject)=>{const tx=db.transaction("conflicts");const request=tx.objectStore("conflicts").getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error)})}
export async function deleteConflict(id:string){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("conflicts","readwrite");tx.objectStore("conflicts").delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
