"use client";
import { useEffect, useState } from "react";
import { deleteConflict, deleteMutation, getAction, getConflicts, getMutations, saveAction, saveConflict, saveMutation, type OfflineAction, type OfflineConflict, type OfflineMutation } from "../offline-store";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Action=OfflineAction; type Session={session_id:string;action:Action;started_at:string}; type Summary={important_done:number;small_done:number;ready:number};
export default function Execute(){const[action,setAction]=useState<Action|null>(null),[session,setSession]=useState<Session|null>(null),[seconds,setSeconds]=useState(600),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[offline,setOffline]=useState(false),[queue,setQueue]=useState<OfflineMutation[]>([]),[conflicts,setConflicts]=useState<OfflineConflict[]>([]);
 function remaining(started:string){return Math.max(0,600-Math.floor((Date.now()-new Date(started).getTime())/1000))}
 async function sync(){const pending=await getMutations();for(const item of pending){try{const r=await fetch(`${API}/api/offline/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});if(r.ok)await deleteMutation(item.id);else if(r.status===409){const body=await r.json().catch(()=>null);await saveConflict({id:item.id,action_id:item.action_id,outcome:item.outcome,detail:body?.detail||"offline conflict",created_at:new Date().toISOString()});await deleteMutation(item.id)}}catch{break}}setQueue(await getMutations());setConflicts(await getConflicts())}
 async function load(){setLoading(true);try{const active=await fetch(`${API}/api/sessions/active`);if(!active.ok)throw new Error("offline");const current=await active.json();if(current){setSession(current);setAction(current.action);setSeconds(remaining(current.started_at));setLoading(false);return}const r=await fetch(`${API}/api/now`);if(!r.ok)throw new Error("offline");const next=await r.json();setAction(next);if(next)await saveAction(next);setOffline(false);await sync()}catch{setOffline(true);const cached=await getAction();if(cached)setAction(cached)}setQueue(await getMutations());setLoading(false)}
 async function start(){if(!action)return;try{if(offline)throw new Error("offline");const r=await fetch(`${API}/api/actions/${action.id}/start`,{method:"POST"});if(!r.ok)throw new Error("start failed");const current=await r.json();setSession(current);setSeconds(remaining(current.started_at))}catch{const started=new Date().toISOString();setSession({session_id:`offline-${Date.now()}`,action,started_at:started});setSeconds(600);setOffline(true);setMessage("Offline gestart. Afronden wordt veilig gesynchroniseerd.")}}
 async function finish(outcome:string,reason?:string){if(!session)return;if(session.session_id.startsWith("offline-")){await saveMutation({id:session.session_id,action_id:session.action.id,outcome,started_at:session.started_at,stuck_reason:reason});setSession(null);setQueue(await getMutations());setMessage("Offline opgeslagen; synchronisatie wacht op verbinding.");return}try{const r=await fetch(`${API}/api/sessions/${session.session_id}/finish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({outcome,stuck_reason:reason})});if(!r.ok)throw new Error("finish failed");setSession(null);setMessage(outcome==="done"?"Klaar. Goed gedaan.":"Opgeslagen.");load()}catch{await saveMutation({id:`offline-${Date.now()}`,action_id:session.action.id,outcome,started_at:session.started_at,stuck_reason:reason});setSession(null);setOffline(true);setQueue(await getMutations());setMessage("Verbinding weg; completion staat in de offline queue.")}}
 useEffect(()=>{load();getConflicts().then(setConflicts);const online=()=>{setOffline(false);sync();load()};const offlineEvent=()=>setOffline(true);window.addEventListener("online",online);window.addEventListener("offline",offlineEvent);return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",offlineEvent)}},[]);useEffect(()=>{if(!session)return;const timer=window.setInterval(()=>setSeconds(remaining(session.started_at)),1000);return()=>window.clearInterval(timer)},[session]);useEffect(()=>{function onKey(event:KeyboardEvent){if(event.key!=="Enter"||event.repeat)return;if((event.target as HTMLElement).tagName==="INPUT"||(event.target as HTMLElement).tagName==="TEXTAREA")return;event.preventDefault();if(session)finish("done");else if(action)start()}window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[action,session]);
 const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 async function dismissConflict(id:string){await deleteConflict(id);setConflicts(await getConflicts())}
 return <main className="execute-shell"><header><span className="logo">ADD</span><span>Do</span><a className="lab-link" href="/">NU</a><span className="header-status">{offline?"Offline":queue.length?`${queue.length} wachtend`:conflicts.length?`${conflicts.length} conflict${conflicts.length===1?"":"en"}`:"Online"}</span></header>{loading?<section className="hero"><p className="meta">Een actie zoeken…</p></section>:session?<section className="hero"><p className="eyebrow">{offline?"OFFLINE BEZIG":"BEZIG"}</p><h1>{session.action.text}</h1><p className="timer">{time}</p><button aria-keyshortcuts="Enter" onClick={()=>finish("done")}>Klaar</button><p className="meta">Enter = klaar</p><details className="execute-options"><summary>Andere uitkomst</summary><div className="actions"><button className="secondary" onClick={()=>finish("continue")}>Nog 10 minuten</button><button className="quiet" onClick={()=>finish("stuck","too_big")}>Ik zit vast</button><button className="quiet" onClick={()=>finish("stop_for_today")}>Stop voor vandaag</button></div></details></section>:action?<section className="hero"><p className="eyebrow">{offline?"OFFLINE KOPIE":"ÉÉN ACTIE"}</p><h1>{action.text}</h1><p className="meta">{action.estimated_minutes} minuten · {action.energy} energie</p><button aria-keyshortcuts="Enter" onClick={start}>Start</button><p className="meta">Enter = starten</p><p className="message">{message}</p></section>:<section className="hero"><p className="eyebrow">RUSTIG</p><h1>Geen actie nodig.</h1><p className="meta">{message}</p><a className="primary-link" href="/intake">Naar Inbox</a></section>}{conflicts.length>0&&<section className="suggestion"><p className="eyebrow">CONFLICT</p><h2>Offline actie niet automatisch overschreven.</h2>{conflicts.map(conflict=><div className="pending-item" key={conflict.id}><div><strong>{conflict.detail}</strong><p>Actie: {conflict.action_id} · uitkomst: {conflict.outcome}</p></div><button className="quiet" onClick={()=>void dismissConflict(conflict.id)}>Conflict gezien</button></div>)}<p className="meta"><a href="/" className="primary-link">Bekijk de actuele actie in NU</a></p></section>}<p className="execute-footer"><a href="/today">Vandaag bekijken</a></p></main>}
