"use client";
import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Account = { id:string; name:string; provider:string; address:string; status:string; last_synced_at:string|null; last_error:string|null };

export default function MailSetup() {
  const [accounts,setAccounts]=useState<Account[]>([]), [name,setName]=useState("Mijn mailbox"), [provider,setProvider]=useState("gmail"), [address,setAddress]=useState(""), [credential,setCredential]=useState("{}"), [message,setMessage]=useState("");
  async function load(){const r=await fetch(`${API}/api/mail/accounts`); if(r.ok)setAccounts(await r.json())}
  useEffect(()=>{void load()},[]);
  async function add(e:React.FormEvent){e.preventDefault();setMessage("");try{const parsed=JSON.parse(credential);const r=await fetch(`${API}/api/mail/accounts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,provider,address,credential:parsed})});setMessage(r.ok?"Mailbox opgeslagen.":"Mailbox kon niet worden opgeslagen.");if(r.ok)await load()}catch{setMessage("Credential-configuratie moet geldige JSON zijn.")}}
  async function sync(){const r=await fetch(`${API}/api/mail/sync`,{method:"POST"});setMessage(r.ok?"Sync afgerond.":"Sync kon niet worden gestart.");await load()}
  async function toggle(id:string){await fetch(`${API}/api/mail/accounts/${id}/pause`,{method:"POST"});await load()}
  async function remove(id:string){await fetch(`${API}/api/mail/accounts/${id}`,{method:"DELETE"});await load()}
  return <main className="security-shell"><header><span className="logo">ADD</span><span>Mail</span><a className="lab-link" href="/integrations">Integraties</a></header><section className="hero"><p className="eyebrow">MAILBOX-WIZARD</p><h1>Breng je mail naar Inbox.</h1><p className="meta">ADD bewaart alleen metadata en korte snippets. Antwoorden worden nooit automatisch verstuurd.</p><form className="intake-form" onSubmit={add}><label>Naam<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="gmail">Gmail OAuth-token</option><option value="outlook">Microsoft Graph-token</option><option value="imap">IMAP</option></select></label><label>Adres<input required type="email" value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Credential JSON<textarea value={credential} onChange={e=>setCredential(e.target.value)} rows={4}/></label><button>Mailbox opslaan</button></form><p className="message">{message}</p></section><section className="context"><div className="pending-heading"><h2>Verbonden mailboxen</h2><button className="quiet" onClick={sync}>Nu synchroniseren</button></div>{accounts.length?accounts.map(account=><article className="pending-item" key={account.id}><div><strong>{account.name} · {account.provider}</strong><p>{account.address} · {account.status}{account.last_synced_at?` · ${new Date(account.last_synced_at).toLocaleString("nl-NL")}`:""}</p>{account.last_error&&<small>{account.last_error}</small>}</div><div className="actions"><button className="quiet" onClick={()=>toggle(account.id)}>{account.status==="active"?"Pauzeren":"Activeren"}</button><button className="quiet" onClick={()=>remove(account.id)}>Verwijderen</button></div></article>):<p className="meta">Nog geen mailbox gekoppeld.</p>}</section></main>
}
