"use client";
import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Mode = "hidden" | "dot" | "count";
type Stage = { count: number; sources?: { source_type: string; count: number }[]; long_open_count?: number; today_count?: number; upcoming_count?: number; missed_count?: number; breakdown?: Record<string, number>; href: string };
type Summary = { inbox: Stage; later: Stage; planned: Stage; review: Stage; next: { key: string; label: string; href: string } };
const labels: Record<string, { title: string; description: string }> = { inbox: { title: "Inbox", description: "Nieuwe items uit al je bronnen." }, later: { title: "Later", description: "Open werk zonder commitment." }, planned: { title: "Gepland", description: "Wat je vandaag of later hebt toegezegd." }, review: { title: "Dagreview", description: "Wat aandacht vraagt na je planning." } };

export default function Overview() {
  const [summary, setSummary] = useState<Summary | null>(null), [mode, setMode] = useState<Mode>("dot"), [error, setError] = useState("");
  async function load() { const [sr, pr] = await Promise.all([fetch(`${API}/api/workflow-summary?timezone=Europe%2FAmsterdam`), fetch(`${API}/api/preferences`)]); if (!sr.ok) { setError("Het workflow-overzicht kon niet worden geladen."); return; } setSummary(await sr.json()); if (pr.ok) setMode((await pr.json()).workflow_badge_mode); }
  useEffect(() => { void load(); }, []);
  function badge(stage: Stage) { if (mode === "hidden" || stage.count === 0) return null; if (mode === "dot") return <span className="workflow-dot" aria-label={`${stage.count} open items`} />; return <span className="workflow-count">{stage.count}</span>; }
  function risk(stage: Stage, key: string) { if (key === "review" && stage.count > 0) return "risk-alert"; if (key === "planned" && stage.missed_count) return "risk-alert"; return ""; }
  return <main className="flow-shell"><header><span className="logo">ADD</span><span>Overzicht</span><a className="lab-link" href="/">NU</a></header>{summary ? <><section className="hero flow-hero"><p className="eyebrow">WORKFLOW</p><h1>Wat vraagt aandacht?</h1><p className="meta">Een rustig overzicht van waar je open werk zich bevindt.</p><div className="flow-line" aria-label="Inbox naar Later naar Gepland naar Dagreview"><span>Inbox</span><i>→</i><span>Later</span><i>→</i><span>Gepland</span><i>→</i><span>Dagreview</span></div></section><section className="workflow-grid" aria-label="Workflowfasen">{(["inbox", "later", "planned", "review"] as const).map(key => { const stage = summary[key]; const copy = labels[key]; return <a className={`workflow-card ${risk(stage, key)}`} href={stage.href} key={key}><div className="workflow-card-top"><span className="eyebrow">{key === "planned" ? "COMMITMENT" : key === "review" ? "REFLECTIE" : key.toUpperCase()}</span>{badge(stage)}</div><h2>{copy.title}</h2><p>{copy.description}</p>{key === "planned" && <strong>{stage.today_count || 0} vandaag{stage.missed_count ? ` · ${stage.missed_count} gemist` : ""}</strong>}{key === "later" && stage.long_open_count ? <strong>{stage.long_open_count} langer open</strong> : null}{key === "review" && stage.breakdown ? <small>{stage.breakdown.open_proposals || 0} voorstellen · {stage.breakdown.overdue || 0} overdue · {stage.breakdown.blocked || 0} vastgelopen</small> : null}{key === "inbox" && stage.sources?.length ? <small>{stage.sources.map(item => `${item.source_type}: ${item.count}`).join(" · ")}</small> : null}</a>; })}</section><section className="flow-next"><p className="eyebrow">VOLGENDE BESLISSING</p><h2>{summary.next.label}</h2><a className="primary-link" href={summary.next.href}>{summary.next.label}</a></section></> : <section className="hero"><p className="meta">Workflow-overzicht laden…</p></section>}{error && <p className="message">{error}</p>}</main>;
}
