"use client";
import { useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Preview={valid:boolean;message:string;counts?:Record<string,number>};
export default function Backup(){const[preview,setPreview]=useState<Preview|null>(null),[payload,setPayload]=useState<unknown>(null),[message,setMessage]=useState(""),[confirm,setConfirm]=useState(false);
 async function download(){const r=await fetch(`${API}/api/backup/export`);if(!r.ok){setMessage("Backup downloaden mislukt.");return}const blob=await r.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`add-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage("Backup gedownload.")}
 async function inspect(file:File){try{const json=JSON.parse(await file.text());const r=await fetch(`${API}/api/backup/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(json)});setPayload(json);setPreview(await r.json());setConfirm(false);setMessage("")}catch{setPreview(null);setMessage("Geen geldige JSON-backup.")}}
 async function restore(){if(!payload)return;const r=await fetch(`${API}/api/backup/restore?confirmed=true`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setMessage(r.ok?"Backup hersteld; rollback-snapshot opgeslagen.":"Restore mislukt of geblokkeerd.");setConfirm(false)}
 async function rollback(){const r=await fetch(`${API}/api/backup/rollback?confirmed=true`,{method:"POST"});setMessage(r.ok?"Vorige toestand teruggezet.":"Geen rollback beschikbaar.")}
 return <main className="backup-shell"><header><span className="logo">ADD</span><span>Backup</span><a className="lab-link" href="/">NU</a></header><section className="hero"><p className="eyebrow">VEILIGHEID</p><h1>Bewaar je ADD-data.</h1><p className="meta">Download, controleer en herstel alleen na een expliciete tweede bevestiging.</p><div className="actions"><button onClick={download}>Backup downloaden</button><label className="secondary upload">Backup controleren<input type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/></label><button className="quiet" onClick={rollback}>Rollback laatste restore</button></div><p className="message">{message}</p></section>{preview&&<section className="suggestion"><p className="eyebrow">{preview.valid?"BACKUP GECONTROLEERD":"ONGELDIG"}</p><h2>{preview.message}</h2>{preview.valid&&!confirm&&<button className="secondary" onClick={()=>setConfirm(true)}>Hersteloptie tonen</button>}{preview.valid&&confirm&&<><p className="meta">Dit vervangt de huidige ADD-data.</p><button onClick={restore}>Ik bevestig herstel</button></>}</section>}</main>}
