"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Action={id:string;text:string};
export default function Unstuck(){const[item,setItem]=useState<Action|null>(null),[show,setShow]=useState(false),[title,setTitle]=useState(""),[step,setStep]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch(`${API}/api/actions?status=blocked`);const items=r.ok?await r.json():[];setItem(items[0]||null);setLoading(false)}
 async function retry(){if(!item)return;const r=await fetch(`${API}/api/actions/${item.id}/resolve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resolution:"retry"})});if(r.ok){setItem(null);setMessage("Opnieuw beschikbaar gemaakt.")}}
 async function smaller(e:React.FormEvent){e.preventDefault();if(!item)return;const r=await fetch(`${API}/api/actions/${item.id}/resolve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resolution:"create_prerequisite",prerequisite_title:title,prerequisite_action:step})});if(r.ok){setItem(null);setMessage("Kleinere stap klaargezet.")}}
 useEffect(()=>{load()},[]);
 return <main className="unstuck-shell"><header><span className="logo">ADD</span><span>Weer op weg</span><a className="lab-link" href="/">NU</a></header>{loading?<section className="hero"><p className="meta">Kijken waar je vastliep…</p></section>:item?<section className="hero"><p className="eyebrow">ÉÉN GEBLOKKEERDE ACTIE</p><h1>{item.text}</h1><p className="meta">Vastlopen is informatie. Kies de kleinste volgende beweging.</p><button onClick={retry}>Opnieuw proberen</button><details className="unstuck-options" open={show} onToggle={e=>setShow((e.target as HTMLDetailsElement).open)}><summary>Maak een kleinere stap</summary><form onSubmit={smaller}><label>Naam<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="bijv. Voorbereiding openen"/></label><label>Eerste stap<input required value={step} onChange={e=>setStep(e.target.value)} placeholder="bijv. Zoek het dossier"/></label><button className="secondary">Kleinere stap klaarzetten</button></form></details></section>:<section className="hero"><p className="eyebrow">RUSTIG</p><h1>{message||"Niets om op te lossen."}</h1><p className="meta">Er zijn geen geblokkeerde acties.</p><a className="primary-link" href="/execute">Eén actie doen</a></section>}<p className="unstuck-footer"><a href="/today">Terug naar Vandaag</a></p></main>}
